# =============================================================================
# OPTIMIZED ADAFEDADAM MEDICAL FEDERATED LEARNING CONFIGURATION
# =============================================================================
# Fixed configuration structure for Flower 1.18.0

# 🎯 Core Training Settings
num-rounds = 20
strategy = "FedAdam"

# 🧠 AdaFedAdam Parameters (FIXED: Research-Optimized for stability)
eta = 0.05          # INCREASED: Server learning rate (was 0.01)
eta-l = 0.005       # INCREASED: Client learning rate (was 0.0001)
beta-1 = 0.9        # First moment decay
beta-2 = 0.999      # Second moment decay
tau = 1e-7          # Numerical stability
alpha = 1.0         # REDUCED: Fairness parameter (was 0.5) - Less aggressive fairness

# 👥 Client Configuration (Flexible for any number of supernodes)
fraction-fit = 1.0
fraction-evaluate = 1.0
min-fit-clients = 1
min-evaluate-clients = 1

# 🏥 Medical Domain Settings (OPTIMIZED for better learning)
local-epochs = 3    # REDUCED: Less overfitting (was 5)
batch-size = 8      # INCREASED: Better gradient estimation (was 4)
test-batch-size = 4
num-classes = 4
img-size = 256
weight-decay = 1e-3 # INCREASED: More regularization (was 1e-4)

# 🛡️ Stability & Performance
round-timeout = 3600  # INCREASED: 1 hour timeout for complex training
enable-global-evaluation = true

# 🔬 Research Features (SIMPLIFIED for stability)
noise-adaptation = false        # DISABLED: Reduce complexity
physics-scheduling = false      # Disabled for stability
progressive-complexity = false  # DISABLED: Reduce complexity

# =============================================================================
# FEDERATION CONFIGURATIONS
# =============================================================================

[tool.flwr.federations]
default = "research"

# 🔬 Research Configuration (1 client - single node testing)
[tool.flwr.federations.research]
options.num-supernodes = 1
options.backend.client-resources.num-cpus = 2
options.backend.client-resources.num-gpus = 0.5
options.backend.timeout = 1200
options.backend.round-timeout = 900

# 🚀 Scalable Configuration (5 clients - extended)
[tool.flwr.federations.scalable]
options.num-supernodes = 5
options.backend.client-resources.num-cpus = 2
options.backend.client-resources.num-gpus = 0.2
options.backend.timeout = 1200
options.backend.round-timeout = 900

# ⚡ High Performance Configuration (10 clients - maximum)
[tool.flwr.federations.high-performance]
options.num-supernodes = 10
options.backend.client-resources.num-cpus = 2
options.backend.client-resources.num-gpus = 0.1
options.backend.timeout = 1200
options.backend.round-timeout = 900

# =============================================================================
# EMERGENCY FIX: HYPERPARAMETERS FOR CATASTROPHIC LOSS RECOVERY
# =============================================================================
# Updated configuration to address Loss=8.5M and Dice≈0 issues

# 🎯 Core Training Settings
num-rounds = 20
strategy = "FedAdam"

# 🧠 AdaFedAdam Parameters (STABILITY OPTIMIZED for medical segmentation)
eta = 0.001         # REDUCED: Conservative server learning rate to prevent divergence
eta-l = 0.0001      # REDUCED: Conservative client learning rate for stability  
beta-1 = 0.9        # First moment decay (stable)
beta-2 = 0.999      # INCREASED: Standard Adam second moment decay for stability
tau = 1e-7          # Standard numerical stability
alpha = 0.5         # Moderate fairness parameter

# 👥 Client Configuration  
local-epochs = 2    # REDUCED: Prevent overfitting and instability
batch-size = 4      # Conservative batch size for stability  
learning-rate = 0.0001 # REDUCED: Conservative learning rate to prevent divergence
weight-decay = 1e-3 # INCREASED: More regularization to prevent overfitting

# 🔍 Data and Model Settings
n-channels = 1
n-classes = 4
dropout-rate = 0.1
use-batch-norm = true
use-residual = true

# 📊 Data Partitioning (FIXED for better convergence)
partitioning-strategy = "dirichlet"
alpha-data = 0.5    # INCREASED: More homogeneous data distribution (was 0.3)
deterministic = true
seed = 42
validate-data = true

# 🎯 Loss and Optimization Settings
gradient-clip-norm = 1.0        # Conservative gradient clipping
enable-early-stopping = true
patience = 3                    # Early stopping patience
enable-detailed-metrics = true

# 🔧 Debugging and Monitoring
enable-data-validation = true   # NEW: Enable comprehensive data validation
enable-gradient-monitoring = true # NEW: Enable gradient flow monitoring
log-level = "INFO"
save-checkpoints = true         # NEW: Save model checkpoints for debugging

# 📱 Federation Environment
data-path = "data/raw/ACDC"
log-dir = "logs"

# [tool.flwr.federations.research] 
num-supernodes = 1
backend = "simulation" 